# Generated by Django 5.2.3 on 2025-08-08 09:52

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('document', models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage, upload_to='file/')),
                ('image', models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage, upload_to='image/')),
                ('passw', models.CharField(max_length=50)),
                ('c_passw', models.CharField(max_length=50)),
            ],
        ),
    ]
