# Generated by Django 5.2.3 on 2025-08-12 06:23

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='vedioo',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage, upload_to='video/'),
        ),
    ]
